spring:
  security:
    user:
      name: user
      password: 123456
  datasource:
    url: jdbc:mysql://localhost:3306/spss
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
  app:
    jwtSecret: mySecretKey123912738aopsgjnspkmndfsopkvajoirjg94gf2opfng2moknm
    jwtExpirationMs: 172800000

logging:
  level.org:
    springframework:
      security: DEBUG
      orm.jpa.JpaBaseConfiguration: ERROR
    hibernate:
      SQL: OFF
      type.descriptor.sql.BasicBinder: OFF
      orm.deprecation: ERROR
      engine.transaction.jta.platform.internal.JtaPlatformInitiator: ERROR